### PR TITLE
fix __FILENAME__ into __FILE__ for DEBUG

### PR DESCRIPTION
**Pull request by bubeck**

### CODE REVIEW

**Comment by fhorinek** [comment]
I prefer the smaller footprint of the __FILENAME__

**Comment by bubeck** [comment]
I get a compile error, that __FILENAME__ is undefined. __FILE__ on the other hand is C Standard: https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

Where is __FILENAME__ defined?

**Comment by fhorinek** [comment]
Are you using CubeIDE?

**Comment by bubeck** [comment]
No, GCC with cmake

**Pull request closed without merging**
